### your site title here

title: Sergei Jegorov
description: Software Engineer | Student

baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: "sejego@taltech.ee"


highlighter: rouge
markdown: kramdown

# Pagination
# paginate: 4
# permalink: /blog/:year/:title/
# paginate_path: /blog/page:num/

# Social media links in footer
email: "sejego@taltech.ee"
linkedin: "sejego"
github: "sejego"
researchgate: "Sergei-Jegorov"
youtube: "UCu6FOB1b0kAYbp5X_c_Z_3g"

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/
  personal:
    output: true
    permalink: /personal/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-target-blank
